<?php

	/*
		The glossary's text preparation -- view.php?action=definitions and
		modify.php's autogenerated definitions.  Every result must still be
		valid UTF-8: until September 2026 this class cut single bytes out of
		multibyte characters, and "voilà", "Россия" and every em dash came
		back broken.
	*/

	class TextCleanupTest extends GGCMSTestCase {
		protected function setUp(): void {
			parent::setUp();

			$this->requireEngine(['file'=>'classes/Language/Grammar.php']);
			$this->requireEngine(['file'=>'classes/Language/TextCleanup.php']);
		}

		public function newTextCleanup() {
			return new TextCleanup(['grammar'=>new Grammar()]);
		}

		public function assertSameUTF8($expected, $actual, $message = '') {
			$this->assertTrue(mb_check_encoding($actual, 'UTF-8'), 'valid UTF-8: ' . $message);
			$this->assertSame($expected, $actual, $message);
		}

		public function testPrepareSentences() {
			$sentences = $this->newTextCleanup()->PrepareSentences(['text'=>'Anarchism: a theory of society without government. Voilà — the idea is Россия. Short.']);

			$this->assertSame(['Anarchism: a theory of society without government', 'a theory of society without government', 'Voilà — the idea is Россия'], $sentences, 'sentences over ten bytes, and the part after a colon');
		}

		public function testGetSubSentences() {
			$text_cleanup = $this->newTextCleanup();

			$this->assertSame([' a theory of society'], $text_cleanup->GetSubSentences(['text'=>'Anarchism: a theory of society']));
			$this->assertSame([], $text_cleanup->GetSubSentences(['text'=>'Word: short']), 'ten bytes or fewer after the colon');
			$this->assertSame([], $text_cleanup->GetSubSentences(['text'=>'no colon at all here']));
		}

		public function testPrepareSentence() {
			$text_cleanup = $this->newTextCleanup();

			$cases = [
				'  voilà déjà vu '=>'voilà déjà vu',
				'Россия Рим'=>'Россия Рим',
				"a\u{00A0}\u{00A0}b"=>'a b',
				"\u{00A0}à\u{00A0}"=>'à',
				"one\r\ntwo\tthree"=>'one two three',
			];

			foreach($cases as $sentence => $expected) {
				$this->assertSameUTF8($expected, $text_cleanup->PrepareSentence(['sentence'=>$sentence]), json_encode($sentence));
			}
		}

		public function testPrepareSentenceFully() {
			$this->assertSameUTF8('déjà vu', $this->newTextCleanup()->PrepareSentenceFully(['sentence'=>'("déjà!" & vu)']));
		}

		public function testEscapeSequencesPattern() {
			$text_cleanup = $this->newTextCleanup();
			$pattern = '/' . $text_cleanup->EscapeSequencesPattern(['escapesequences'=>$text_cleanup->GetEscapeSequences()]) . '/';

			$this->assertSame(1, preg_match($pattern, "\u{00A0}"), 'the UTF-8 no-break space');
			$this->assertSame(1, preg_match($pattern, "a\xA0b"), 'a bare Latin-1 one after ASCII');
			$this->assertSame(0, preg_match($pattern, 'à'), 'never the tail of a-grave, C3 A0');
			$this->assertSame(0, preg_match($pattern, 'Р'), 'never the tail of Cyrillic Er, D0 A0');
		}

		public function testGetEscapeSequences() {
			$this->assertSame("\xC2\xA0 \xA0 \r\n", $this->newTextCleanup()->GetEscapeSequences());
		}

		public function testGetFullEscapeSequences() {
			$this->assertSame("\xC2\xA0 \xA0 !\"#\$%&'()\r\n", $this->newTextCleanup()->GetFullEscapeSequences());
		}

		public function testCleanupTextBeforeEscaping() {
			$this->assertSameUTF8("He said 'no'  —  it's Гора, is not it", $this->newTextCleanup()->CleanupTextBeforeEscaping(['text'=>'He said “no” — it’s Гора, isn‘t it']));
		}

		public function testEscapeSinglePhrase() {
			$escaped = $this->newTextCleanup()->EscapeSinglePhrase(['line'=>'In the U.S.A. today', 'escapethis'=>['U.S.A.']]);

			$this->assertSame(' In the U_S_A_ today ', $escaped, 'periods that do not end a sentence are hidden');
		}

		public function testUnescapeSinglePhrase() {
			$this->assertSame('  In the U.S.A. today  ', $this->newTextCleanup()->UnescapeSinglePhrase(['line'=>' In the U_S_A_ today ', 'escapethis'=>['U.S.A.']]));
		}

		public function testCleansePhrase() {
			$this->assertSameUTF8('déjà', $this->newTextCleanup()->CleansePhrase(['phrase'=>'—*déjà_-']));
			$this->assertSameUTF8('Россия', $this->newTextCleanup()->CleansePhrase(['phrase'=>' Россия ']), 'Cyrillic ending in D0 xx survives');
		}

		public function testCleansePhraseFully() {
			$this->assertSameUTF8('Россия', $this->newTextCleanup()->CleansePhraseFully(['phrase'=>'“Россия—”']));
			$this->assertSameUTF8('Д', $this->newTextCleanup()->CleansePhraseFully(['phrase'=>'Д']), 'D0 94: its tail is the old cp1252 right quote');
			$this->assertSameUTF8('word', $this->newTextCleanup()->CleansePhraseFully(['phrase'=>'*“word”!?']));
		}

		public function testBuildWords() {
			$this->assertSame(['à', 'la', 'carte'], $this->newTextCleanup()->BuildWords(['sentence'=>'à la Carte']));
		}

		public function testBuildWordsFully() {
			$this->assertSame(['déjà', 'vu'], $this->newTextCleanup()->BuildWordsFully(['sentence'=>'("Déjà" vu!)']));
		}
	}

?>
