<?php
error_reporting(E_ALL);
set_error_handler(function($n,$m){throw new ErrorException($m,0,$n);});
require __DIR__.'/abstract-base-format-stub.php';
require dirname(__DIR__,3).'/src/classes/Format/RSS.php';
class TitleFixture extends RSS {
 public $rows;
 public function RunTemplates(){}
 public function ConvertHTMLToFormat_renderImage($args){return '';}
 public function ConvertHTMLToFormat_lastBuildDate(){return '2026-09-10';}
 public function getEntries(){return $this->rows;}
 public function ConvertHTMLToFormat_renderContent_FormattedDescription($args){return 'Description';}
}
$failed=0;libxml_use_internal_errors(TRUE);foreach([0.91,2.0] as $version){
foreach(['Plain','A & B','<b>Title</b>','Literal &amp; entity',"Caf\u{00e9} 'quoted'"] as $value){$shown=html_entity_decode($value,ENT_QUOTES|ENT_HTML5,'UTF-8');
 $feed=new TitleFixture();$feed->version=(string)$version;$feed->version_float=$version;$feed->section_separator='';$feed->line_separator='';$feed->indent_levels=[1=>'',2=>'',3=>''];$feed->human_readable=FALSE;
 $feed->script=new class($value) {public $entry,$record_list=[],$parent=['ChildNoun'=>'Book','GrandChildNoun'=>'Chapter'];public function __construct($value){$this->entry=['Title'=>$value,'Subtitle'=>$value,'OriginalCreationDate'=>'2026-09-10'];}public function getDescription(){return 'Description';}};
 $feed->rows=[['Title'=>$value,'Subtitle'=>$value,'GrandParent_Title'=>$value,'Parent_Title'=>$value,'GrandParent_Code'=>'','Parent_Code'=>'','Code'=>'entry','OriginalCreationDate'=>'2026-09-10','association'=>[],'PermaLinkid'=>7]];
 $feed->handler=(object)['cleanser'=>(object)['utf8_characters'=>new class {public function SystemCharSet(){return 'UTF-8';}}],'domain'=>new class {public function GetPrimaryDomain($args){return 'https://example.test';}},'version'=>new class {public $text;public function GetSoftwareNameAcronymAndVersion(){return $this->text;}},'globals'=>new class {public $text;public function AdminEmailAddress(){return $this->text;}public function AdminName(){return $this->text;}public function SiteCategory(){return 'Books';}}];
 $feed->handler->globals->text=$value;$feed->handler->version->text=$value;$feed->script->parent['ChildNoun']=$value;
 $xml=$feed->ConvertHTMLToFormat();$doc=new DOMDocument();$ok=$doc->loadXML($xml,LIBXML_NONET);
 if($ok){$xpath=new DOMXPath($doc);$xpath->registerNamespace('a','http://www.w3.org/2005/Atom');$ok=$xpath->evaluate('string(/rss/channel/title)')===$shown.': '.$shown&&$xpath->evaluate('string(/rss/channel/item/title)')==='['.$shown.'] '.$shown.' -- '.$shown.': '.$shown&&$xpath->query('//title/*')->length===0;}
 if($ok){foreach(['managingEditor','webMaster'] as $field){$ok=$ok&&$xpath->evaluate('string(/rss/channel/'.$field.')')===$shown.' ('.$shown.')';}
 $field=$version>=2?'generator':'copyright';$expected='RSS Feed Generated by '.$shown.($version>=2?', Released Under BSD 3-Clause License.':', Released Under BSD 3-Clause License.  The contents of this feed are otherwise in the Public Domain.');
 $ok=$ok&&$xpath->evaluate('string(/rss/channel/'.$field.')')===$expected;
 if($version>=0.92){$ok=$ok&&$xpath->evaluate('string(/rss/channel/item/category)')===$shown;}
 $ok=$ok&&$xpath->query('//managingEditor/*|//webMaster/*|//generator/*|//copyright/*|//category/*')->length===0;}
 libxml_clear_errors();echo ($ok?'PASS ':'FAIL ').'RSS metadata '.json_encode($value).PHP_EOL;if(!$ok){$failed++;}
}
}
exit($failed?1:0);