#!/usr/bin/php
<?php

	/*
		Freezes style.php's atomic classes into one static stylesheet.

		style.php built each page's stylesheet on request from a manifest,
		templates/<site>/<script>/<action>_css.php, listing classes such as
		width/width-90percent.css.  The markup of every site still carries
		those classes, so they have to keep working while the modules move
		to real stylesheets -- see Docs/Styling.md.  This writes every class
		any manifest names, on any site, using style.php's own methods, into
		src/css/legacy.css.  Run it again only if a manifest gains a class.

		From a checkout:

			GGCMS_CONFIG_REPO=/path/to/GreenGluonCMS_Unhireable \
			php build_legacy_css.php

		Writes nothing but src/css/legacy.css.
	*/

	$config_repo = rtrim(str_replace(DIRECTORY_SEPARATOR, '/', (string) getenv('GGCMS_CONFIG_REPO')), '/');

	if(!strlen($config_repo) || !is_dir($config_repo . '/usr/lib/ggcms/src/templates')) {
		fwrite(STDERR, "GGCMS_CONFIG_REPO must name the private configuration repository: every site's manifests are in its templates.\n");
		exit(1);
	}

	$engine_dir = dirname(__DIR__, 4) . '/src/';

		/*
			style.php extends the CSS format's basicscript, which needs the
			whole format machinery.  Only its three spacing methods are used
			on the path taken here, so a stand-in carries just those.
		*/

	class basicscript {
		public function DisplaySingleTab() {
			print("\t");
		}

		public function DisplaySingleReturn() {
			print("\n");
		}

		public function DisplayDoubleReturns() {
			print("\n\n");
		}
	}

	require($engine_dir . 'scripts/style.php');

	$manifest_lines = [];

	foreach([$engine_dir . 'templates', $config_repo . '/usr/lib/ggcms/src/templates'] as $templates_dir) {
		$files = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($templates_dir, FilesystemIterator::SKIP_DOTS));

		foreach($files as $file) {
			if(substr($file->getFilename(), -8) !== '_css.php') {
				continue;
			}

			foreach(file($file->getPathname()) as $line) {
				$line = trim($line);

				if(strlen($line)) {
					$manifest_lines[$line] = TRUE;
				}
			}
		}
	}

	$manifest_lines = array_keys($manifest_lines);
	sort($manifest_lines);

	$generator = new class extends style {
		public function __construct() {
			$this->format = new class {
				public function OneCSSFilePerPage() {
					return 1;
				}
			};

			$this->handler = (object) [
				'cleanser'=>new class {
					public function CleanseInput_Integer($args) {
						return ['cleansedinput'=>(int) $args['input']];
					}
				},
			];
		}
	};

	$generator->script_css_file_locations = $manifest_lines;

	ob_start();
	$generator->Display_Attributes();
	$rules = ob_get_clean();

	$header = <<<'CSS'
/*
	legacy.css -- GENERATED by cli/scripts/internal/style/build_legacy_css.php.
	Do not edit by hand; run the script again.

	Every atomic class any template manifest names, on any site, as
	style.php printed it.  It sits in the "legacy" layer, below the
	components, so a converted module's own rules win without !important.
	See Docs/Styling.md.
*/


CSS;

	$destination = $engine_dir . 'css/legacy.css';

	if(!is_dir(dirname($destination))) {
		mkdir(dirname($destination), 0755, TRUE);
	}

	file_put_contents($destination, $header . '@layer legacy {' . "\n\n" . $rules . "\n" . '}' . "\n");

	print(count($manifest_lines) . ' manifest entries, ' . substr_count($rules, '{') . ' rules -> ' . $destination . "\n");

?>
